/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedMovementsRouteImport } from './routes/_authenticated/movements'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedRepRouteRouteImport } from './routes/_authenticated/rep/route'
import { Route as AuthenticatedSupervisorIndexRouteImport } from './routes/_authenticated/supervisor.index'
import { Route as AuthenticatedRepIndexRouteImport } from './routes/_authenticated/rep/index'
import { Route as AuthenticatedDeveloperIndexRouteImport } from './routes/_authenticated/developer.index'
import { Route as AuthenticatedSupervisorRoutesRouteImport } from './routes/_authenticated/supervisor.routes'
import { Route as AuthenticatedSupervisorReportsRouteImport } from './routes/_authenticated/supervisor.reports'
import { Route as AuthenticatedSupervisorLiveRouteImport } from './routes/_authenticated/supervisor.live'
import { Route as AuthenticatedRepSaleRouteImport } from './routes/_authenticated/rep/sale'
import { Route as AuthenticatedRepPlanRouteImport } from './routes/_authenticated/rep/plan'
import { Route as AuthenticatedRepCustomersRouteImport } from './routes/_authenticated/rep/customers'
import { Route as AuthenticatedRepAttendanceRouteImport } from './routes/_authenticated/rep/attendance'
import { Route as AuthenticatedDeveloperTenantsRouteImport } from './routes/_authenticated/developer.tenants'
import { Route as AuthenticatedDeveloperModulesRouteImport } from './routes/_authenticated/developer.modules'
import { Route as AuthenticatedDashboardRepsRouteImport } from './routes/_authenticated/dashboard.reps'
import { Route as AuthenticatedDashboardProfitabilityRouteImport } from './routes/_authenticated/dashboard.profitability'
import { Route as AuthenticatedDashboardForecastRouteImport } from './routes/_authenticated/dashboard.forecast'
import { Route as AuthenticatedDashboardExecutiveRouteImport } from './routes/_authenticated/dashboard.executive'
import { Route as AuthenticatedRepVisitCustomerIdRouteImport } from './routes/_authenticated/rep/visit.$customerId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovementsRoute = AuthenticatedMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepRouteRoute = AuthenticatedRepRouteRouteImport.update({
  id: '/rep',
  path: '/rep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorIndexRoute =
  AuthenticatedSupervisorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedRepIndexRoute = AuthenticatedRepIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRepRouteRoute,
} as any)
const AuthenticatedDeveloperIndexRoute =
  AuthenticatedDeveloperIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedSupervisorRoutesRoute =
  AuthenticatedSupervisorRoutesRouteImport.update({
    id: '/routes',
    path: '/routes',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedSupervisorReportsRoute =
  AuthenticatedSupervisorReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedSupervisorLiveRoute =
  AuthenticatedSupervisorLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedSupervisorRoute,
  } as any)
const AuthenticatedRepSaleRoute = AuthenticatedRepSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => AuthenticatedRepRouteRoute,
} as any)
const AuthenticatedRepPlanRoute = AuthenticatedRepPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRepRouteRoute,
} as any)
const AuthenticatedRepCustomersRoute =
  AuthenticatedRepCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedRepRouteRoute,
  } as any)
const AuthenticatedRepAttendanceRoute =
  AuthenticatedRepAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedRepRouteRoute,
  } as any)
const AuthenticatedDeveloperTenantsRoute =
  AuthenticatedDeveloperTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDeveloperModulesRoute =
  AuthenticatedDeveloperModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedDeveloperRoute,
  } as any)
const AuthenticatedDashboardRepsRoute =
  AuthenticatedDashboardRepsRouteImport.update({
    id: '/dashboard/reps',
    path: '/dashboard/reps',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProfitabilityRoute =
  AuthenticatedDashboardProfitabilityRouteImport.update({
    id: '/dashboard/profitability',
    path: '/dashboard/profitability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardForecastRoute =
  AuthenticatedDashboardForecastRouteImport.update({
    id: '/dashboard/forecast',
    path: '/dashboard/forecast',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardExecutiveRoute =
  AuthenticatedDashboardExecutiveRouteImport.update({
    id: '/dashboard/executive',
    path: '/dashboard/executive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepVisitCustomerIdRoute =
  AuthenticatedRepVisitCustomerIdRouteImport.update({
    id: '/visit/$customerId',
    path: '/visit/$customerId',
    getParentRoute: () => AuthenticatedRepRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/rep': typeof AuthenticatedRepRouteRouteWithChildren
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/developer': typeof AuthenticatedDeveloperRouteWithChildren
  '/finance': typeof AuthenticatedFinanceRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supervisor': typeof AuthenticatedSupervisorRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/dashboard/executive': typeof AuthenticatedDashboardExecutiveRoute
  '/dashboard/forecast': typeof AuthenticatedDashboardForecastRoute
  '/dashboard/profitability': typeof AuthenticatedDashboardProfitabilityRoute
  '/dashboard/reps': typeof AuthenticatedDashboardRepsRoute
  '/developer/modules': typeof AuthenticatedDeveloperModulesRoute
  '/developer/tenants': typeof AuthenticatedDeveloperTenantsRoute
  '/rep/attendance': typeof AuthenticatedRepAttendanceRoute
  '/rep/customers': typeof AuthenticatedRepCustomersRoute
  '/rep/plan': typeof AuthenticatedRepPlanRoute
  '/rep/sale': typeof AuthenticatedRepSaleRoute
  '/supervisor/live': typeof AuthenticatedSupervisorLiveRoute
  '/supervisor/reports': typeof AuthenticatedSupervisorReportsRoute
  '/supervisor/routes': typeof AuthenticatedSupervisorRoutesRoute
  '/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/rep/': typeof AuthenticatedRepIndexRoute
  '/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/rep/visit/$customerId': typeof AuthenticatedRepVisitCustomerIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboard/executive': typeof AuthenticatedDashboardExecutiveRoute
  '/dashboard/forecast': typeof AuthenticatedDashboardForecastRoute
  '/dashboard/profitability': typeof AuthenticatedDashboardProfitabilityRoute
  '/dashboard/reps': typeof AuthenticatedDashboardRepsRoute
  '/developer/modules': typeof AuthenticatedDeveloperModulesRoute
  '/developer/tenants': typeof AuthenticatedDeveloperTenantsRoute
  '/rep/attendance': typeof AuthenticatedRepAttendanceRoute
  '/rep/customers': typeof AuthenticatedRepCustomersRoute
  '/rep/plan': typeof AuthenticatedRepPlanRoute
  '/rep/sale': typeof AuthenticatedRepSaleRoute
  '/supervisor/live': typeof AuthenticatedSupervisorLiveRoute
  '/supervisor/reports': typeof AuthenticatedSupervisorReportsRoute
  '/supervisor/routes': typeof AuthenticatedSupervisorRoutesRoute
  '/developer': typeof AuthenticatedDeveloperIndexRoute
  '/rep': typeof AuthenticatedRepIndexRoute
  '/supervisor': typeof AuthenticatedSupervisorIndexRoute
  '/rep/visit/$customerId': typeof AuthenticatedRepVisitCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/rep': typeof AuthenticatedRepRouteRouteWithChildren
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRouteWithChildren
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/movements': typeof AuthenticatedMovementsRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dashboard/executive': typeof AuthenticatedDashboardExecutiveRoute
  '/_authenticated/dashboard/forecast': typeof AuthenticatedDashboardForecastRoute
  '/_authenticated/dashboard/profitability': typeof AuthenticatedDashboardProfitabilityRoute
  '/_authenticated/dashboard/reps': typeof AuthenticatedDashboardRepsRoute
  '/_authenticated/developer/modules': typeof AuthenticatedDeveloperModulesRoute
  '/_authenticated/developer/tenants': typeof AuthenticatedDeveloperTenantsRoute
  '/_authenticated/rep/attendance': typeof AuthenticatedRepAttendanceRoute
  '/_authenticated/rep/customers': typeof AuthenticatedRepCustomersRoute
  '/_authenticated/rep/plan': typeof AuthenticatedRepPlanRoute
  '/_authenticated/rep/sale': typeof AuthenticatedRepSaleRoute
  '/_authenticated/supervisor/live': typeof AuthenticatedSupervisorLiveRoute
  '/_authenticated/supervisor/reports': typeof AuthenticatedSupervisorReportsRoute
  '/_authenticated/supervisor/routes': typeof AuthenticatedSupervisorRoutesRoute
  '/_authenticated/developer/': typeof AuthenticatedDeveloperIndexRoute
  '/_authenticated/rep/': typeof AuthenticatedRepIndexRoute
  '/_authenticated/supervisor/': typeof AuthenticatedSupervisorIndexRoute
  '/_authenticated/rep/visit/$customerId': typeof AuthenticatedRepVisitCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/rep'
    | '/categories'
    | '/customers'
    | '/developer'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/movements'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/supervisor'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/dashboard/executive'
    | '/dashboard/forecast'
    | '/dashboard/profitability'
    | '/dashboard/reps'
    | '/developer/modules'
    | '/developer/tenants'
    | '/rep/attendance'
    | '/rep/customers'
    | '/rep/plan'
    | '/rep/sale'
    | '/supervisor/live'
    | '/supervisor/reports'
    | '/supervisor/routes'
    | '/developer/'
    | '/rep/'
    | '/supervisor/'
    | '/rep/visit/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/categories'
    | '/customers'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/movements'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/'
    | '/dashboard/executive'
    | '/dashboard/forecast'
    | '/dashboard/profitability'
    | '/dashboard/reps'
    | '/developer/modules'
    | '/developer/tenants'
    | '/rep/attendance'
    | '/rep/customers'
    | '/rep/plan'
    | '/rep/sale'
    | '/supervisor/live'
    | '/supervisor/reports'
    | '/supervisor/routes'
    | '/developer'
    | '/rep'
    | '/supervisor'
    | '/rep/visit/$customerId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/rep'
    | '/_authenticated/categories'
    | '/_authenticated/customers'
    | '/_authenticated/developer'
    | '/_authenticated/finance'
    | '/_authenticated/hr'
    | '/_authenticated/inventory'
    | '/_authenticated/movements'
    | '/_authenticated/pos'
    | '/_authenticated/products'
    | '/_authenticated/purchases'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/supervisor'
    | '/_authenticated/suppliers'
    | '/_authenticated/users'
    | '/_authenticated/warehouses'
    | '/_authenticated/'
    | '/_authenticated/dashboard/executive'
    | '/_authenticated/dashboard/forecast'
    | '/_authenticated/dashboard/profitability'
    | '/_authenticated/dashboard/reps'
    | '/_authenticated/developer/modules'
    | '/_authenticated/developer/tenants'
    | '/_authenticated/rep/attendance'
    | '/_authenticated/rep/customers'
    | '/_authenticated/rep/plan'
    | '/_authenticated/rep/sale'
    | '/_authenticated/supervisor/live'
    | '/_authenticated/supervisor/reports'
    | '/_authenticated/supervisor/routes'
    | '/_authenticated/developer/'
    | '/_authenticated/rep/'
    | '/_authenticated/supervisor/'
    | '/_authenticated/rep/visit/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movements': {
      id: '/_authenticated/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AuthenticatedMovementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rep': {
      id: '/_authenticated/rep'
      path: '/rep'
      fullPath: '/rep'
      preLoaderRoute: typeof AuthenticatedRepRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor/': {
      id: '/_authenticated/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof AuthenticatedSupervisorIndexRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/rep/': {
      id: '/_authenticated/rep/'
      path: '/'
      fullPath: '/rep/'
      preLoaderRoute: typeof AuthenticatedRepIndexRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/developer/': {
      id: '/_authenticated/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof AuthenticatedDeveloperIndexRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/supervisor/routes': {
      id: '/_authenticated/supervisor/routes'
      path: '/routes'
      fullPath: '/supervisor/routes'
      preLoaderRoute: typeof AuthenticatedSupervisorRoutesRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/supervisor/reports': {
      id: '/_authenticated/supervisor/reports'
      path: '/reports'
      fullPath: '/supervisor/reports'
      preLoaderRoute: typeof AuthenticatedSupervisorReportsRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/supervisor/live': {
      id: '/_authenticated/supervisor/live'
      path: '/live'
      fullPath: '/supervisor/live'
      preLoaderRoute: typeof AuthenticatedSupervisorLiveRouteImport
      parentRoute: typeof AuthenticatedSupervisorRoute
    }
    '/_authenticated/rep/sale': {
      id: '/_authenticated/rep/sale'
      path: '/sale'
      fullPath: '/rep/sale'
      preLoaderRoute: typeof AuthenticatedRepSaleRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/rep/plan': {
      id: '/_authenticated/rep/plan'
      path: '/plan'
      fullPath: '/rep/plan'
      preLoaderRoute: typeof AuthenticatedRepPlanRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/rep/customers': {
      id: '/_authenticated/rep/customers'
      path: '/customers'
      fullPath: '/rep/customers'
      preLoaderRoute: typeof AuthenticatedRepCustomersRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/rep/attendance': {
      id: '/_authenticated/rep/attendance'
      path: '/attendance'
      fullPath: '/rep/attendance'
      preLoaderRoute: typeof AuthenticatedRepAttendanceRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/developer/tenants': {
      id: '/_authenticated/developer/tenants'
      path: '/tenants'
      fullPath: '/developer/tenants'
      preLoaderRoute: typeof AuthenticatedDeveloperTenantsRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/developer/modules': {
      id: '/_authenticated/developer/modules'
      path: '/modules'
      fullPath: '/developer/modules'
      preLoaderRoute: typeof AuthenticatedDeveloperModulesRouteImport
      parentRoute: typeof AuthenticatedDeveloperRoute
    }
    '/_authenticated/dashboard/reps': {
      id: '/_authenticated/dashboard/reps'
      path: '/dashboard/reps'
      fullPath: '/dashboard/reps'
      preLoaderRoute: typeof AuthenticatedDashboardRepsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/profitability': {
      id: '/_authenticated/dashboard/profitability'
      path: '/dashboard/profitability'
      fullPath: '/dashboard/profitability'
      preLoaderRoute: typeof AuthenticatedDashboardProfitabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/forecast': {
      id: '/_authenticated/dashboard/forecast'
      path: '/dashboard/forecast'
      fullPath: '/dashboard/forecast'
      preLoaderRoute: typeof AuthenticatedDashboardForecastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/executive': {
      id: '/_authenticated/dashboard/executive'
      path: '/dashboard/executive'
      fullPath: '/dashboard/executive'
      preLoaderRoute: typeof AuthenticatedDashboardExecutiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rep/visit/$customerId': {
      id: '/_authenticated/rep/visit/$customerId'
      path: '/visit/$customerId'
      fullPath: '/rep/visit/$customerId'
      preLoaderRoute: typeof AuthenticatedRepVisitCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
  }
}

interface AuthenticatedRepRouteRouteChildren {
  AuthenticatedRepAttendanceRoute: typeof AuthenticatedRepAttendanceRoute
  AuthenticatedRepCustomersRoute: typeof AuthenticatedRepCustomersRoute
  AuthenticatedRepPlanRoute: typeof AuthenticatedRepPlanRoute
  AuthenticatedRepSaleRoute: typeof AuthenticatedRepSaleRoute
  AuthenticatedRepIndexRoute: typeof AuthenticatedRepIndexRoute
  AuthenticatedRepVisitCustomerIdRoute: typeof AuthenticatedRepVisitCustomerIdRoute
}

const AuthenticatedRepRouteRouteChildren: AuthenticatedRepRouteRouteChildren = {
  AuthenticatedRepAttendanceRoute: AuthenticatedRepAttendanceRoute,
  AuthenticatedRepCustomersRoute: AuthenticatedRepCustomersRoute,
  AuthenticatedRepPlanRoute: AuthenticatedRepPlanRoute,
  AuthenticatedRepSaleRoute: AuthenticatedRepSaleRoute,
  AuthenticatedRepIndexRoute: AuthenticatedRepIndexRoute,
  AuthenticatedRepVisitCustomerIdRoute: AuthenticatedRepVisitCustomerIdRoute,
}

const AuthenticatedRepRouteRouteWithChildren =
  AuthenticatedRepRouteRoute._addFileChildren(
    AuthenticatedRepRouteRouteChildren,
  )

interface AuthenticatedDeveloperRouteChildren {
  AuthenticatedDeveloperModulesRoute: typeof AuthenticatedDeveloperModulesRoute
  AuthenticatedDeveloperTenantsRoute: typeof AuthenticatedDeveloperTenantsRoute
  AuthenticatedDeveloperIndexRoute: typeof AuthenticatedDeveloperIndexRoute
}

const AuthenticatedDeveloperRouteChildren: AuthenticatedDeveloperRouteChildren =
  {
    AuthenticatedDeveloperModulesRoute: AuthenticatedDeveloperModulesRoute,
    AuthenticatedDeveloperTenantsRoute: AuthenticatedDeveloperTenantsRoute,
    AuthenticatedDeveloperIndexRoute: AuthenticatedDeveloperIndexRoute,
  }

const AuthenticatedDeveloperRouteWithChildren =
  AuthenticatedDeveloperRoute._addFileChildren(
    AuthenticatedDeveloperRouteChildren,
  )

interface AuthenticatedSupervisorRouteChildren {
  AuthenticatedSupervisorLiveRoute: typeof AuthenticatedSupervisorLiveRoute
  AuthenticatedSupervisorReportsRoute: typeof AuthenticatedSupervisorReportsRoute
  AuthenticatedSupervisorRoutesRoute: typeof AuthenticatedSupervisorRoutesRoute
  AuthenticatedSupervisorIndexRoute: typeof AuthenticatedSupervisorIndexRoute
}

const AuthenticatedSupervisorRouteChildren: AuthenticatedSupervisorRouteChildren =
  {
    AuthenticatedSupervisorLiveRoute: AuthenticatedSupervisorLiveRoute,
    AuthenticatedSupervisorReportsRoute: AuthenticatedSupervisorReportsRoute,
    AuthenticatedSupervisorRoutesRoute: AuthenticatedSupervisorRoutesRoute,
    AuthenticatedSupervisorIndexRoute: AuthenticatedSupervisorIndexRoute,
  }

const AuthenticatedSupervisorRouteWithChildren =
  AuthenticatedSupervisorRoute._addFileChildren(
    AuthenticatedSupervisorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRepRouteRoute: typeof AuthenticatedRepRouteRouteWithChildren
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRouteWithChildren
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMovementsRoute: typeof AuthenticatedMovementsRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDashboardExecutiveRoute: typeof AuthenticatedDashboardExecutiveRoute
  AuthenticatedDashboardForecastRoute: typeof AuthenticatedDashboardForecastRoute
  AuthenticatedDashboardProfitabilityRoute: typeof AuthenticatedDashboardProfitabilityRoute
  AuthenticatedDashboardRepsRoute: typeof AuthenticatedDashboardRepsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRepRouteRoute: AuthenticatedRepRouteRouteWithChildren,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRouteWithChildren,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMovementsRoute: AuthenticatedMovementsRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDashboardExecutiveRoute: AuthenticatedDashboardExecutiveRoute,
  AuthenticatedDashboardForecastRoute: AuthenticatedDashboardForecastRoute,
  AuthenticatedDashboardProfitabilityRoute:
    AuthenticatedDashboardProfitabilityRoute,
  AuthenticatedDashboardRepsRoute: AuthenticatedDashboardRepsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
