/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedMovementsRouteImport } from './routes/_authenticated/movements'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedRepRouteRouteImport } from './routes/_authenticated/rep/route'
import { Route as AuthenticatedRepIndexRouteImport } from './routes/_authenticated/rep/index'
import { Route as AuthenticatedRepSaleRouteImport } from './routes/_authenticated/rep/sale'
import { Route as AuthenticatedRepPlanRouteImport } from './routes/_authenticated/rep/plan'
import { Route as AuthenticatedRepCustomersRouteImport } from './routes/_authenticated/rep/customers'
import { Route as AuthenticatedRepAttendanceRouteImport } from './routes/_authenticated/rep/attendance'
import { Route as AuthenticatedRepVisitCustomerIdRouteImport } from './routes/_authenticated/rep/visit.$customerId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovementsRoute = AuthenticatedMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepRouteRoute = AuthenticatedRepRouteRouteImport.update({
  id: '/rep',
  path: '/rep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepIndexRoute = AuthenticatedRepIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRepRouteRoute,
} as any)
const AuthenticatedRepSaleRoute = AuthenticatedRepSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => AuthenticatedRepRouteRoute,
} as any)
const AuthenticatedRepPlanRoute = AuthenticatedRepPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRepRouteRoute,
} as any)
const AuthenticatedRepCustomersRoute =
  AuthenticatedRepCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedRepRouteRoute,
  } as any)
const AuthenticatedRepAttendanceRoute =
  AuthenticatedRepAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedRepRouteRoute,
  } as any)
const AuthenticatedRepVisitCustomerIdRoute =
  AuthenticatedRepVisitCustomerIdRouteImport.update({
    id: '/visit/$customerId',
    path: '/visit/$customerId',
    getParentRoute: () => AuthenticatedRepRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/rep': typeof AuthenticatedRepRouteRouteWithChildren
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/rep/attendance': typeof AuthenticatedRepAttendanceRoute
  '/rep/customers': typeof AuthenticatedRepCustomersRoute
  '/rep/plan': typeof AuthenticatedRepPlanRoute
  '/rep/sale': typeof AuthenticatedRepSaleRoute
  '/rep/': typeof AuthenticatedRepIndexRoute
  '/rep/visit/$customerId': typeof AuthenticatedRepVisitCustomerIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/hr': typeof AuthenticatedHrRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/movements': typeof AuthenticatedMovementsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/': typeof AuthenticatedIndexRoute
  '/rep/attendance': typeof AuthenticatedRepAttendanceRoute
  '/rep/customers': typeof AuthenticatedRepCustomersRoute
  '/rep/plan': typeof AuthenticatedRepPlanRoute
  '/rep/sale': typeof AuthenticatedRepSaleRoute
  '/rep': typeof AuthenticatedRepIndexRoute
  '/rep/visit/$customerId': typeof AuthenticatedRepVisitCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/rep': typeof AuthenticatedRepRouteRouteWithChildren
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/movements': typeof AuthenticatedMovementsRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/rep/attendance': typeof AuthenticatedRepAttendanceRoute
  '/_authenticated/rep/customers': typeof AuthenticatedRepCustomersRoute
  '/_authenticated/rep/plan': typeof AuthenticatedRepPlanRoute
  '/_authenticated/rep/sale': typeof AuthenticatedRepSaleRoute
  '/_authenticated/rep/': typeof AuthenticatedRepIndexRoute
  '/_authenticated/rep/visit/$customerId': typeof AuthenticatedRepVisitCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/rep'
    | '/categories'
    | '/customers'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/movements'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/supervisor'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/rep/attendance'
    | '/rep/customers'
    | '/rep/plan'
    | '/rep/sale'
    | '/rep/'
    | '/rep/visit/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/categories'
    | '/customers'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/movements'
    | '/pos'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/supervisor'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/'
    | '/rep/attendance'
    | '/rep/customers'
    | '/rep/plan'
    | '/rep/sale'
    | '/rep'
    | '/rep/visit/$customerId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/rep'
    | '/_authenticated/categories'
    | '/_authenticated/customers'
    | '/_authenticated/finance'
    | '/_authenticated/hr'
    | '/_authenticated/inventory'
    | '/_authenticated/movements'
    | '/_authenticated/pos'
    | '/_authenticated/products'
    | '/_authenticated/purchases'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/supervisor'
    | '/_authenticated/suppliers'
    | '/_authenticated/users'
    | '/_authenticated/warehouses'
    | '/_authenticated/'
    | '/_authenticated/rep/attendance'
    | '/_authenticated/rep/customers'
    | '/_authenticated/rep/plan'
    | '/_authenticated/rep/sale'
    | '/_authenticated/rep/'
    | '/_authenticated/rep/visit/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movements': {
      id: '/_authenticated/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AuthenticatedMovementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rep': {
      id: '/_authenticated/rep'
      path: '/rep'
      fullPath: '/rep'
      preLoaderRoute: typeof AuthenticatedRepRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rep/': {
      id: '/_authenticated/rep/'
      path: '/'
      fullPath: '/rep/'
      preLoaderRoute: typeof AuthenticatedRepIndexRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/rep/sale': {
      id: '/_authenticated/rep/sale'
      path: '/sale'
      fullPath: '/rep/sale'
      preLoaderRoute: typeof AuthenticatedRepSaleRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/rep/plan': {
      id: '/_authenticated/rep/plan'
      path: '/plan'
      fullPath: '/rep/plan'
      preLoaderRoute: typeof AuthenticatedRepPlanRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/rep/customers': {
      id: '/_authenticated/rep/customers'
      path: '/customers'
      fullPath: '/rep/customers'
      preLoaderRoute: typeof AuthenticatedRepCustomersRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/rep/attendance': {
      id: '/_authenticated/rep/attendance'
      path: '/attendance'
      fullPath: '/rep/attendance'
      preLoaderRoute: typeof AuthenticatedRepAttendanceRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
    '/_authenticated/rep/visit/$customerId': {
      id: '/_authenticated/rep/visit/$customerId'
      path: '/visit/$customerId'
      fullPath: '/rep/visit/$customerId'
      preLoaderRoute: typeof AuthenticatedRepVisitCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRepRouteRoute
    }
  }
}

interface AuthenticatedRepRouteRouteChildren {
  AuthenticatedRepAttendanceRoute: typeof AuthenticatedRepAttendanceRoute
  AuthenticatedRepCustomersRoute: typeof AuthenticatedRepCustomersRoute
  AuthenticatedRepPlanRoute: typeof AuthenticatedRepPlanRoute
  AuthenticatedRepSaleRoute: typeof AuthenticatedRepSaleRoute
  AuthenticatedRepIndexRoute: typeof AuthenticatedRepIndexRoute
  AuthenticatedRepVisitCustomerIdRoute: typeof AuthenticatedRepVisitCustomerIdRoute
}

const AuthenticatedRepRouteRouteChildren: AuthenticatedRepRouteRouteChildren = {
  AuthenticatedRepAttendanceRoute: AuthenticatedRepAttendanceRoute,
  AuthenticatedRepCustomersRoute: AuthenticatedRepCustomersRoute,
  AuthenticatedRepPlanRoute: AuthenticatedRepPlanRoute,
  AuthenticatedRepSaleRoute: AuthenticatedRepSaleRoute,
  AuthenticatedRepIndexRoute: AuthenticatedRepIndexRoute,
  AuthenticatedRepVisitCustomerIdRoute: AuthenticatedRepVisitCustomerIdRoute,
}

const AuthenticatedRepRouteRouteWithChildren =
  AuthenticatedRepRouteRoute._addFileChildren(
    AuthenticatedRepRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRepRouteRoute: typeof AuthenticatedRepRouteRouteWithChildren
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMovementsRoute: typeof AuthenticatedMovementsRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRepRouteRoute: AuthenticatedRepRouteRouteWithChildren,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMovementsRoute: AuthenticatedMovementsRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
